version: "3"
services:
  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

# TODO добавить сервисы
  gateway:
      image: gateway
      build: ./Gateway/
      ports:
        - "8080:8080"
      depends_on:
        - cars
        - rental
        - payment
      environment:
        PORT: 8080
      
  cars:
      image: cars
      build: ./Cars/
      ports:
        - "8070:8070"
      depends_on:
        - postgres
      environment:
        DATABASE_URL: "postgres://program:test@postgres:5432/cars"
        PORT: 8070
      
  rental:
      image: rental
      build: ./Rental/
      ports:
        - "8060:8060"
      depends_on:
        - postgres
      environment:
        PORT: 8060
     
  payment:
      image: payment
      build: ./Payment/
      ports:
        - "8050:8050"
      depends_on:
        - postgres
      environment:
        PORT: 8050

volumes:
  db-data: