domain: toastonfire.cloud.okteto.net
gateway:
  name: gateway
  repo: toastonfire/rsoi-lab4:gateway
  port: 8080
cars:
  name: cars
  repo: toastonfire/rsoi-lab4:cars
  port: 8070
payment:
  name: payment
  repo: toastonfire/rsoi-lab4:payment
  port: 8050
rental:
  name: rental
  repo: toastonfire/rsoi-lab4:rental
  port: 8060
postgres:
  name: postgres
  repo: library/postgres:13
  port: 5432
  default_database:
    name: postgres
    user: postgres
    password: postgres
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      cpu: 200m
      memory: 1024Mi