name: GitHub Classroom Workflow
on:
  push:
    branches: [ master ]
env:
  OKTETO_SERVER: ${{ secrets.OKTETO_SERVER }}
  OKTETO_TOKEN: ${{ secrets.OKTETO_TOKEN }}
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: docker/setup-buildx-action@v2

      # TODO build, publish to docker hub, deploy to k8s
      
      - name: Login in dockerhub
        uses: docker/login-action@v2
        with:
          username: toastonfire
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      
      - name: Build docker images
        run: |
          docker build ./Cars/ -t toastonfire/rsoi-lab4:cars
          docker build ./Gateway/ -t toastonfire/rsoi-lab4:gateway
          docker build ./Payment/ -t toastonfire/rsoi-lab4:payment
          docker build ./Rental/ -t toastonfire/rsoi-lab4:rental
          
      - name: Push docker images
        run: |
          docker push toastonfire/rsoi-lab4:cars
          docker push toastonfire/rsoi-lab4:gateway
          docker push toastonfire/rsoi-lab4:payment
          docker push toastonfire/rsoi-lab4:rental
          
      - name: Deploy to Okteto
        run: |
          kubectl config set-cluster cars-service-cluster --server="$OKTETO_SERVER" --insecure-skip-tls-verify=true
          kubectl config set-credentials cloud_okteto_com-user --token="$OKTETO_TOKEN"
          kubectl config set-context default --cluster=cars-service-cluster --user=cloud_okteto_com-user --namespace="toastonfire"
          kubectl config use-context default
          helm install services ./k8s/services-chart
          sleep 60

      - name: Run API Tests
        uses: matt-ball/newman-action@master
        with:
          collection: v3/postman/collection.json
          environment: v3/postman/environment.json
          delayRequest: 100
          reporters: '[ "cli" ]'

      - uses: education/autograding@v1
        id: autograder
        continue-on-error: true

      - name: Github auto grader mark
        uses: Romanow/google-sheet-autograder-marker@v1.0
        with:
          google_token: ${{secrets.GOOGLE_API_KEY}}
          sheet_id: "1xkgjUX6Qmk7rdJG-QPOToav-HWWtthJjnShIKnw3oIY"
          homework_number: 4
          user_column: 'D'
          column_offset: 'F'
          mark: "'+"